import { FlexCol, Icon, Typography } from "@shared";
import dotSvg from "@assets/common/dot.svg";
import React from "react";
import { Address } from "viem";
import {
  multiplyETH_ADDRESS_STRATEGY_ID,
  wstETHBooster_ADDRESS_STRATEGY_ID,
} from "../../../../../state/settings/config";

const faqsData = {
  [wstETHBooster_ADDRESS_STRATEGY_ID]: [
    {
      question: <>Am I exposed to ETH price with this ILM?</>,
      answer: (
        <>
          No. Since wstETH and ETH are correlated assets, regardless of ETH price movement, you earn staking fees from
          holding a larger wstETH balance.
        </>
      ),
    },
    {
      question: <>Where does the yield come from with this ILM?</>,
      answer: (
        <>
          APY comes from staking fee rewards generated by holding wstETH. Participants in this ILM are also eligible for
          wstETH bonus rewards.
        </>
      ),
    },
    {
      question: <>Are there any costs with this ILM?</>,
      answer: (
        <>
          To achieve the 3x loop, ETH is swapped into wstETH. There are costs associated from Dexes to swap as well as
          slippage, however Seamless does not charge any extra fees. These costs occur on deposit & withdrawal from the
          ILM.
        </>
      ),
    },
    {
      question: <>Where can I see my rewards and my position balance?</>,
      answer: <>Head to the “My Positions” Tab to see your ILM LP Token Balance and underlying wstETH Balance.</>,
    },
  ],
  [multiplyETH_ADDRESS_STRATEGY_ID]: [
    {
      question: <>Am I exposed to ETH price with this ILM?</>,
      answer: <>Yes. As ETH increases in price, returns are magnified in bullish market conditions.</>,
    },
    {
      question: <>Are there any costs with this ILM?</>,
      answer: (
        <>
          To achieve the 1.5x loop, USDC is swapped into ETH. There are costs associated from Dexes to swap as well as
          slippage, however Seamless does not charge any extra fees. These costs occur on deposit & withdrawal from the
          ILM.
        </>
      ),
    },
    {
      question: <>Where can I see my rewards and my position balance?</>,
      answer: <>Head to the “My Positions” Tab to see your ILM LP Token Balance and underlying ETH Balance.</>,
    },
  ],
};

const FAQItem: React.FC<{
  question: React.ReactNode;
  answer: React.ReactNode;
}> = ({ question, answer }) => (
  <div className="mb-4">
    <div className="flex items-center">
      <Icon src={dotSvg} alt="dot" width={24} />
      <Typography type="bold2" className="ml-[-4px]">
        {question}
      </Typography>
    </div>
    <div className="pl-7">
      <Typography type="medium2">{answer}</Typography>
    </div>
  </div>
);

export const FAQ: React.FC<{
  asset: Address;
  isStrategy?: boolean;
}> = ({ asset, isStrategy }) => {
  if (!isStrategy || !faqsData[asset]) return null;

  return (
    <FlexCol>
      {faqsData[asset].map((faq, index) => (
        <FAQItem key={index} question={faq.question} answer={faq.answer} />
      ))}
    </FlexCol>
  );
};
