name: FrontendDeploymentAction

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present #todo build:prod

      - name: Rename dist folder
        run: |
          TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)
          mv dist "${TIMESTAMP}_${GITHUB_SHA}"

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.FILEBASE_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.FILEBASE_SECRET_KEY }}
          aws-region: us-east-1

      - name: Upload to IPFS
        env:
          FILEBASE_ACCESS_KEY: ${{ secrets.FILEBASE_ACCESS_KEY }}
          FILEBASE_SECRET_KEY: ${{ secrets.FILEBASE_SECRET_KEY }}
        run: |
          aws --endpoint https://s3.filebase.com s3 sync ${TIMESTAMP}_${GITHUB_SHA} s3://test/${TIMESTAMP}_${GITHUB_SHA}
